import random
from typing import List, Tuple, Dict

MIN_RANDOM_VALUE = 2
MAX_RANDOM_VALUE = 30

italian_cities = [
    "Roma",
    "Milano",
    "Napoli",
    "Torino",
    "Firenze",
    "Venezia",
    "Bologna",
    "Genova",
    "Palermo",
    "Catania",
    "Verona",
    "Trieste",
    "Padova",
    "Bari",
    "Parma",
    "Brescia",
    "Taranto",
    "Prato",
    "Modena",
    "Reggio Calabria",
    "Reggio Emilia",
    "Perugia",
    "Livorno",
    "Cagliari",
    "Foggia",
    "Ravenna",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Latina",
    "Giugliano in Campania",
    "Monza",
    "Siracusa",
    "Pescara",
    "Bergamo",
    "Forlì",
    "Trento",
    "Vicenza",
    "Terni",
    "Bolzano",
    "Novara",
    "Piacenza",
    "Ancona",
    "Andria",
    "Udine",
    "Arezzo",
    "Cesena",
    "Lecce",
    "Pesaro",
    "Barletta",
    "Alessandria",
    "La Spezia",
    "Pisa",
    "Catanzaro",
    "Potenza",
    "Massa",
    "Trapani",
    "Cosenza",
    "Aversa",
    "Viterbo",
    "Caserta",
    "Novi Sad",
    "Pistoia",
    "Guidonia Montecelio",
    "Lamezia Terme",
    "Faenza",
    "Civitavecchia",
    "Pomezia",
    "Molfetta",
    "Fano",
    "San Severo",
    "Velletri",
    "Avellino",
    "Teramo",
    "Acerra",
    "Imola",
    "Carpi",
    "Viareggio",
    "Agrigento",
    "Caltanissetta",
    "Trani",
    "Benevento",
    "Cuneo",
    "Marano di Napoli",
    "Siena",
    "Crotone",
    "Casoria",
    "April",
    "Afragola",
    "Scandicci",
    "Asti",
    "Gela",
    "Cremona",
    "Fiumicino",
    "L’Aquila",
    "Castellammare di Stabia",
    "Grosseto",
    "Pozzuoli",
    "Brindisi",
    "Pavia",
    "Massa Carrara",
    "Casalnuovo di Napoli",
    "Gorizia",
    "Vercelli",
    "Ercolano",
    "Civitanova Marche",
    "Savona",
    "Belluno",
    "Concesio",
    "Macerata",
]


shopping_list = [
    "Milk",
    "Coffee",
    "Butter",
    "Pens",
    "Bread",
    "Eggs",
    "Cheese",
    "Toothpaste",
    "Shampoo",
    "Soap",
    "Cereal",
    "Rice",
    "Pasta",
    "Tomatoes",
    "Onions",
    "Potatoes",
    "Chicken",
    "Beef",
    "Fish",
    "Apples",
    "Bananas",
    "Oranges",
    "Grapes",
    "Strawberries",
    "Lettuce",
    "Carrots",
    "Cucumbers",
    "Bell Peppers",
    "Spinach",
    "Yogurt",
    "Ice Cream",
    "Cookies",
    "Chips",
    "Soda",
    "Water",
    "Juice",
    "Candles",
    "Matches",
    "Tissues",
    "Toilet Paper",
    "Laundry Detergent",
    "Dish Soap",
    "Trash Bags",
    "Batteries",
    "Light Bulbs",
    "Paper Towels",
    "Aluminum Foil",
    "Plastic Wrap",
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Salad Dressing",
    "Peanut Butter",
    "Jelly",
    "Bakery Goods",
    "Flour",
    "Sugar",
    "Salt",
    "Pepper",
    "Olive Oil",
    "Vinegar",
    "Tea",
    "Coffeemaker",
    "Toaster",
    "Microwave",
    "Trash Can",
    "Broom",
    "Mop",
    "Dustpan",
    "Bucket",
    "Sponges",
    "Cleaning Wipes",
    "Towels",
    "Sheets",
    "Pillowcases",
    "Blankets",
    "Clothing",
    "Shoes",
    "Socks",
    "Underwear",
    "Detergent",
    "Fabric Softener",
    "Razors",
    "Toothbrush",
    "Floss",
    "Bandages",
    "Medicine",
    "First Aid Kit",
]


def random_city() -> str:
    return random.choice(italian_cities)


def random_item() -> str:
    return random.choice(shopping_list)


def random_item_value() -> int:
    return random.randint(MIN_RANDOM_VALUE, MAX_RANDOM_VALUE)


def merch_maker(minproducts, maxproducts) -> Dict[str, int]:
    merch = {}
    for i in range(random.randint(minproducts, maxproducts)):
        item = random_item()
        qty = random_item_value()
        merch.update({item: qty})
    return merch
